#!/usr/bin/env bash

set -eou pipefail

srcdir=./resources/shaders/src
outdir=./resources/shaders/spv
glslc_bin=./vulkan-1.4.321.1/x86_64/bin/glslc

shaders=$(find ./resources/shaders/src -type f)

mkdir -p "$outdir"

for shader in $shaders; do
   echo "compiling: $shader"
   relpath=${shader#"$srcdir"/}
   outfile="$outdir/${relpath%.glsl}.spv"
   mkdir -p "$(dirname "$outfile")"
   "$glslc_bin" "$shader" -o "$outfile"
done

echo "Compiled $(echo "$shaders" | wc -l) shaders to $outdir"
